package com.br.game_library.entity;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;


/**
 * Entity JPA represents a Game in the {@code game} table.
 * <p>
 * Getters, Setter, constructors, builder,{@code equals}/{@code hashCode}, and
 * {@code toString} are generated by Lombok
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Entity
@Table(name = "game")
public class Game {

    @Schema(description = "Unique ID identifier of game")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Schema(description = "Unique ID identifier of steam_app_id")
    @Column(name = "steam_app_id")
    private Long steamAppId;

    @Schema(description = "Game title")
    @Column(nullable = false, length = 150)
    private String title;

    @Schema(description = "Game genre")
    @Column(length = 100)
    private String genre;

    @Schema(description = "Game platform")
    @Column(length = 50)
    private String platform;

    @Schema(description = "Game release_year")
    @Column(name = "release_year")
    private Integer releaseYear;

    @Schema(description = "Game rating")
    @Column(name = "rating")
    private Double rating;

    @Schema(description = "Game description")
    @Column(columnDefinition = "TEXT")
    private String description;

    @Schema(description = "Game image_url")
    @Column(name = "image_url")
    private String imageUrl;

    @Schema(description = "Game favorite")
    @Column(name = "favorite")
    private Boolean favorite;
}
